name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      - name: Build and test
        run: xcodebuild test -scheme ViewCondition -destination 'platform=iOS Simulator,name=iPhone 15 Pro'

  test-macos:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      - name: Build and test
        run: xcodebuild test -scheme ViewCondition -destination 'platform=macOS,arch=x86_64'
