name: Deploy Docs

on:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: macos-14

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5

      - name: Build docs
        run: swift package --allow-writing-to-directory ./docs generate-documentation --target ViewCondition --disable-indexing --output-path ./docs --transform-for-static-hosting --hosting-base-path ViewCondition

      - uses: actions/upload-pages-artifact@v2
        with:
          path: "docs"

      - uses: actions/deploy-pages@v4
        id: deployment
